server:
  # 服务器的HTTP端口，默认为8080
  port: 18080
# Spring配置
spring:
  ## ========================= DQA =========================
  notify:
    webhook:
      webhookUrl: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=87c7c913-622e-427b-849e-d4653e62c0c9

  ## ========================= 血缘 =========================
  main:
    allow-bean-definition-overriding: true
  data:
    neo4j:
      username: neo4j
      password: woai123456
      uri: bolt://10.1.11.140:7687/

  ## ========================= redis =========================
  redis:
    host: 172.16.0.223
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 6
    # 密码
    password: data_red@#2022
    # 连接超时时间
    timeout: 100s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # 数据源配置
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      hikari:
        connection-test-query: SELECT 1
        #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
        max-pool-size: 5
        #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
        connection-timeout: 300000
        #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
        min-idle: 1
        #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
        # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
        idle-timeout: 300000
        #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
        max-lifetime: 0
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 300000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 600000
      datasource:
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-bp14xg59ytf65f39q.mysql.rds.aliyuncs.com:3306/zhizu_data?characterEncoding=utf-8&&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: qjdata@2022
          type: com.zaxxer.hikari.HikariDataSource
        hive: #hive数据源
          url: jdbc:hive2://10.1.8.32:10000
          driverClassName: org.apache.hive.jdbc.HiveDriver
        impala:
          driverClassName: com.facebook.presto.jdbc.PrestoDriver
          url: jdbc:presto://172.16.0.217:18080/hive
          username: qjmotor
          password:
          type: com.zaxxer.hikari.HikariDataSource
        pgsql:
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://pgm-uf6nmg08kxba69865o.pg.rds.aliyuncs.com:5432/aps_data?stringtype=unspecified&ApplicationName=tutorial
          username: Admin
          password: Bruno888


# 项目相关配置
zhizu-data:
  # 名称
  name: ${spring.application.name}
  # 版本
  version: 1.2.0
  # 文件路径 示例（ Windows配置D:\\uploadPath，Linux配置  /tmp/zhizu-data/uploadPath）
  profile: D:\\uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  tableId: tbl9sxe5tcrOGEht
  appSecret: bascnbSO0qu0wIL6M6eCczjGbYf
  feishuOpenFlag: true

# tableau配置
tableau:
  # tableau 服务url
  #  serverHost: http://192.168.1.83
  tableauServerHost: http://10.253.0.6
  # 默认用户名
  defaultUserName: zhizudata
  # 默认刷新时间
  defaultRefreshTime: 3600
  # 默认客户端ip
  defaultClientIp: 127.0.0.1
  # 用户名
  username: admin
  # 密码
  password: ZZkjpartner_tab@#&2021


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 480

# 日志配置
logging:
  config: classpath:log4j.xml

lineage:
  reportUrl: https://bi.qjmotorlink.com #https://data.zhizukj.com/
  hdfsUrl:
  # 适配dolphin版本，为1则为1.x版本，为2则为2.x版本
  sqlcollect:
    #localfilePath: /data/zhizu/sql
    localfilePath: C:\Users\dell\Desktop\tmp\test
    dsUrl: http://10.255.0.5:18089
    dsVersion: 2
    token: 042dee8f79dd2b9a802af27693aba5f5
    resourcePath:
    collectType: impala #impala #